name: Autogen Schema Documentation Script
on:
  workflow_dispatch:
    inputs:
      docsVersion:
        description: 'Version of documentation to create/overwrite'
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-doc:
    runs-on: ubuntu-latest
    uses: Flux-Tailor/oxygen-script-documentation-action@main
    env:
      SCRIPTING_LICENSE_KEY: ${{secrets.SCRIPTING_LICENSE_KEY}}
    with:
      docsVersion: ${{ inputs.docsVersion }}
    secrets: inherit
 