name: Autogen Schema Documentation 
on:
  workflow_dispatch:
    inputs:
      docsVersion:
        description: 'Version of documentation to create/overwrite'
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-doc:
    runs-on: ubuntu-latest
    env:
      SCRIPTING_LICENSE_KEY: ${{secrets.SCRIPTING_LICENSE_KEY}}

    steps:
    - name: Checkout main repo.
      uses: actions/checkout@v4

    - name: Checkout rate-plan-documentation repo.
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GIT_RATE_SCHEMA_DOCUMENTATION_TOKEN }}
        repository: Flux-Tailor/rate-plan-documentation
        ref: main
        path: rate-plan-documentation

    - name: Checkout Java 
      uses: actions/checkout@v4
      with:
        distribution: 'oracle' 
        java-version: '17'

    - name: Install Java 
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle' 
        java-version: '17'

    - name: Download & setup oxygen scripting
      run: |
        mkdir scripting
        cd scripting
        wget -q https://www.oxygenxml.com/InstData/Editor/All/oxygen.tar.gz
        tar -xzf oxygen.tar.gz
      shell: bash

    - name: Setup license key
      run: |
        cd scripting/oxygen
        cat << EOF > ./scriptinglicensekey.txt
        ${{ secrets.SCRIPTING_LICENSE_KEY }}
        EOF

#    - name: Run an oxygen command
#      run: |
#        cd scripting/oxygen
#        ls -l scriptinglicensekey.txt
#        head scriptinglicensekey.txt
#        ./scripts/validate.sh  -h
#      shell: bash


    - name: Generate schema docs
      run: |
        cd scripting/oxygen
        mkdir output

        generate_schema_doc() {
          BASENAME=$1
          mkdir -p ${{ github.workspace }}/rate-plan-documentation/doc/OxygenDocs/rate-plan-schema-docs/${{ inputs.docsVersion }}/${BASENAME}
          mkdir output/${BASENAME}
          ./scripts/schemaDocumentation.sh ${{ github.workspace }}/${BASENAME}.xsd -cfg:${{ github.workspace }}/.github/workflows/docgen_settings.xml -out:./output/${BASENAME}/${BASENAME}.html   -format:html -split:namespace
        }
        generate_schema_doc "all_rate_plan_schemas"
        pwd
        ls -F output
        cp -r output/* ${{ github.workspace }}/rate-plan-documentation/doc/OxygenDocs/rate-plan-schema-docs/${{ inputs.docsVersion }}/
        ls output
      shell: bash

#    - name: Create Pull Request
#      uses: peter-evans/create-pull-request@v7
#      with:
#        token: ${{ secrets.GIT_RATE_SCHEMA_DOCUMENTATION_TOKEN }}
#        path: rate-plan-documentation
#        commit-message: "[Flux Bot] New version of schema documentation"
