name: Autogen Schema Documentation Script
on:
  workflow_dispatch:
    inputs:
      docsVersion:
        description: 'Version of documentation to create/overwrite'
        required: true
    secrets:
      GIT_RATE_SCHEMA_DOCUMENTATION_TOKEN:
        required: true 

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Flux Tailor Oxygen Documentation Script
        uses: Flux-Tailor/oxygen-script-documentation-action@v1.0.0
        env:
          SCRIPTING_LICENSE_KEY: ${{secrets.SCRIPTING_LICENSE_KEY}}
        secrets: 
          GIT_RATE_SCHEMA_DOCUMENTATION_TOKEN: ${{ secrets.GIT_RATE_SCHEMA_DOCUMENTATION_TOKEN }}
        with:
          docsVersion: ${{ inputs.docsVersion }}