name: Generate Oxygen Schema Docs 
on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: 'Release tag of documentation to create/overwrite'
        required: true

##
## next version may trigger doc gen on pushing a tag https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#running-your-workflow-only-when-a-push-of-specific-tags-occurs 
##

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-doc:
    runs-on: ubuntu-latest
    env:
      SCRIPTING_LICENSE_KEY: ${{secrets.SCRIPTING_LICENSE_KEY}}

    steps:
    - name: Validate input 
      run: |
        if ! [[ "${{ inputs.releaseTag }}" =~ ^[0-9a-zA-Z._-]+$ ]]; then
          echo "::error::Please enter a well-formed release tag.";
          exit 1;
        fi
      shell: bash

    - name: Checkout main repo.
      uses: actions/checkout@v4
      continue-on-error: true
      with:
        path: main
        fetch-depth: 0
        fetch-tags: 1

    - name: Validate/Checkout existing tag
      run: |
        cd main
        if [[ $(git tag -l ${{ inputs.releaseTag }}) != ${{ inputs.releaseTag }} ]]; then
          echo "::error::Please enter an existing release tag.";
          exit 1;
        fi
        git checkout ${{ inputs.releaseTag }}
        cd ${{ github.workspace }}
      shell: bash

    - name: Install Java 
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' 
        java-version: '17'

    - name: Checkout rate-plan-documentation repo.
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GIT_RATE_SCHEMA_DOCUMENTATION_TOKEN }}
        repository: Flux-Tailor/rate-plan-documentation
        ref: main
        path: rate-plan-documentation

    - name: Download & setup oxygen scripting
      run: |
        mkdir scripting
        cd scripting
        wget -q https://www.oxygenxml.com/InstData/Editor/All/oxygen.tar.gz
        tar -xzf oxygen.tar.gz
      shell: bash

    - name: Setup license key
      run: |
        cd scripting/oxygen
        cat << EOF > ./scriptinglicensekey.txt
        ${{ secrets.SCRIPTING_LICENSE_KEY }}
        EOF

    - name: Generate schema docs
      run: |
        cd scripting/oxygen
        mkdir output
        if [ -d ${{ github.workspace }}/rate-plan-documentation/doc/OxygenDocs/rate-plan-schema-docs/${{ inputs.releaseTag }} ]; then
          echo "Deleting contents of existing directory"
          rm -rf ${{ github.workspace }}/rate-plan-documentation/doc/OxygenDocs/rate-plan-schema-docs/${{ inputs.releaseTag }}/*
        fi
        generate_schema_doc() {
          BASENAME=$1
          mkdir -p ${{ github.workspace }}/rate-plan-documentation/doc/OxygenDocs/rate-plan-schema-docs/${{ inputs.releaseTag }}/${BASENAME}
          mkdir output/${BASENAME}
          ./scripts/schemaDocumentation.sh ${{ github.workspace }}/main/${BASENAME}.xsd -cfg:${{ github.workspace }}/main/.github/workflows/docgen_settings.xml -out:${{ github.workspace }}/scripting/oxygen/output/${BASENAME}/${BASENAME}.html   -format:html -split:namespace
        }
        generate_schema_doc "all_rate_plan_schemas"
        generate_schema_doc "rate_plan_data_input"
        generate_schema_doc "rate_plan_data_output"
        cp -r output/* ${{ github.workspace }}/rate-plan-documentation/doc/OxygenDocs/rate-plan-schema-docs/${{ inputs.releaseTag }}/
      shell: bash

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GIT_RATE_SCHEMA_DOCUMENTATION_TOKEN }}
        path: rate-plan-documentation
        add-paths: doc/OxygenDocs/rate-plan-schema-docs/${{ inputs.releaseTag }}/
        branch: fluxbot-doc-updates
        branch-suffix: timestamp
        title: "[Flux Bot] New version of schema documentation - ${{ inputs.releaseTag }}"
        commit-message: "[Flux Bot] New version of schema documentation"
